services:
  redis:
    restart: always
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    restart: always
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile.db
    env_file: ../.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    restart: always
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    env_file: ../.env
    volumes:
      - ../backend:/app/src
    depends_on:
      - postgres
      - redis

  nginx:
    restart: always
    image: nginx:alpine
    environment:
      TZ: America/Chihuahua
    volumes:
      - ../docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../backend/static:/www/static:ro
    depends_on:
      - backend
    ports:
      - "8080:80"
  
volumes:
  pgdata:
